export const products = [
  {
    name: 'Classic T-Shirt',
    description: 'Soft cotton T-shirt',
    brand: 'Acme',
    options: ['Color', 'Size', 'Material'],
    variants: [
      {
        color: 'Red',
        size: 'S',
        material: 'Cotton',
        price: 19.99,
        sku: 'TSHIRT-RED-S-COT',
        stock: 10,
        images: ['tshirt-red-front.jpg', 'tshirt-red-back.jpg'],
      },
      {
        color: 'Red',
        size: 'M',
        material: 'Cotton',
        price: 20.99,
        sku: 'TSHIRT-RED-M-COT',
        stock: 8,
        images: ['tshirt-red-front.jpg', 'tshirt-red-back.jpg'],
      },
      {
        color: 'Blue',
        size: 'L',
        material: 'Cotton',
        price: 22.99,
        sku: 'TSHIRT-BLU-L-COT',
        stock: 5,
        images: ['tshirt-blue-front.jpg', 'tshirt-blue-back.jpg'],
      },
    ],
  },

  {
    name: 'Premium Hoodie',
    description: 'Warm fleece hoodie with front pocket',
    brand: 'NorthWind',
    options: ['Color', 'Size', 'Material'],
    variants: [
      {
        color: 'Black',
        size: 'M',
        material: 'Fleece',
        price: 45.99,
        sku: 'HOODIE-BLK-M-FLC',
        stock: 12,
        images: ['hoodie-black-front.jpg', 'hoodie-black-back.jpg'],
      },
      {
        color: 'Black',
        size: 'L',
        material: 'Fleece',
        price: 47.99,
        sku: 'HOODIE-BLK-L-FLC',
        stock: 6,
        images: ['hoodie-black-front.jpg', 'hoodie-black-back.jpg'],
      },
      {
        color: 'Gray',
        size: 'S',
        material: 'Fleece',
        price: 42.99,
        sku: 'HOODIE-GRY-S-FLC',
        stock: 9,
        images: ['hoodie-gray-front.jpg', 'hoodie-gray-back.jpg'],
      },
    ],
  },

  {
    name: 'Sport Running Shoes',
    description: 'Lightweight breathable shoes for running',
    brand: 'FlyStep',
    options: ['Color', 'Size', 'Material'],
    variants: [
      {
        color: 'Black',
        size: '40',
        material: 'Mesh',
        price: 59.99,
        sku: 'RUNBLK-40-MSH',
        stock: 15,
        images: ['shoes-black-left.jpg', 'shoes-black-right.jpg'],
      },
      {
        color: 'Black',
        size: '42',
        material: 'Mesh',
        price: 59.99,
        sku: 'RUNBLK-42-MSH',
        stock: 8,
        images: ['shoes-black-left.jpg', 'shoes-black-right.jpg'],
      },
      {
        color: 'Blue',
        size: '41',
        material: 'Mesh',
        price: 62.99,
        sku: 'RUNBLU-41-MSH',
        stock: 10,
        images: ['shoes-blue-left.jpg', 'shoes-blue-right.jpg'],
      },
    ],
  },

  {
    name: 'Baseball Cap',
    description: 'Adjustable cotton cap with embroidered logo',
    brand: 'UrbanStyle',
    options: ['Color', 'Size', 'Material'],
    variants: [
      {
        color: 'Black',
        size: 'One Size',
        material: 'Cotton',
        price: 14.99,
        sku: 'CAP-BLK-OS-COT',
        stock: 25,
        images: ['cap-black-front.jpg', 'cap-black-back.jpg'],
      },
      {
        color: 'Red',
        size: 'One Size',
        material: 'Cotton',
        price: 14.99,
        sku: 'CAP-RED-OS-COT',
        stock: 20,
        images: ['cap-red-front.jpg', 'cap-red-back.jpg'],
      },
    ],
  },

  {
    name: 'Slim Fit Jeans',
    description: 'Denim jeans with stretch comfort',
    brand: 'DenimPro',
    options: ['Color', 'Size', 'Material'],
    variants: [
      {
        color: 'Dark Blue',
        size: '32',
        material: 'Denim',
        price: 39.99,
        sku: 'JEAN-DB-32-DNM',
        stock: 14,
        images: ['jeans-darkblue-front.jpg', 'jeans-darkblue-back.jpg'],
      },
      {
        color: 'Dark Blue',
        size: '34',
        material: 'Denim',
        price: 39.99,
        sku: 'JEAN-DB-34-DNM',
        stock: 9,
        images: ['jeans-darkblue-front.jpg', 'jeans-darkblue-back.jpg'],
      },
      {
        color: 'Black',
        size: '32',
        material: 'Denim',
        price: 42.99,
        sku: 'JEAN-BLK-32-DNM',
        stock: 6,
        images: ['jeans-black-front.jpg', 'jeans-black-back.jpg'],
      },
    ],
  },
];
